import { test, expect } from '@playwright/test';
import LZString from 'lz-string';

test.beforeEach(async ({ page }) => {
  await page.route('https://**/*', route => route.abort());
  await page.addInitScript(() => localStorage.setItem('cookie-notice-dismissed', 'true'));
});
test('sample failures, field navigation, passing data, and responsive light/dark UI', async ({ page }, info) => {
  await page.goto('/json-schema-validator/');
  await page.locator('#doctor-invalid').click();
  await expect(page.locator('#doctor-findings .doctor-finding')).toHaveCount(4);
  await expect(page.locator('#doctor-summary')).toContainText('Document: invalid');
  await page.locator('#doctor-findings button').filter({ hasText: '/items/0/quantity' }).click();
  expect(await page.locator('#doctor-json').evaluate((e: HTMLTextAreaElement) => e.value[e.selectionStart])).toBe('0');
  await page.screenshot({ path: info.outputPath('schema-doctor-light.png'), fullPage: false });
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  await page.screenshot({ path: info.outputPath('schema-doctor-dark.png'), fullPage: false });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#doctor-valid').click();
  await expect(page.locator('#doctor-summary')).toContainText('Document: valid');
  await expect(page.locator('#doctor-findings')).toContainText('No values were changed');
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', 'https://bugdays.com/json-schema-validator/');
});
test('auto-validation, syntax failure, schema-only and format toggle', async ({ page }) => {
  await page.goto('/json-schema-validator/');
  await page.locator('#doctor-schema').fill('{"type":"string","format":"email"}');
  await page.locator('#doctor-json').fill('"not-an-email"');
  await expect(page.locator('#doctor-summary')).toContainText('Document: valid');
  await page.locator('#doctor-formats').check();
  await expect(page.locator('#doctor-summary')).toContainText('Document: invalid');
  await page.locator('#doctor-json').fill('{"a":}');
  await expect(page.locator('#doctor-findings')).toContainText('Invalid JSON');
  await page.locator('#doctor-json').fill('');
  await expect(page.locator('#doctor-summary')).toContainText('Document: not checked');
  await page.locator('#doctor-schema').fill('{"type":"unknown"}');
  await expect(page.locator('#doctor-summary')).toContainText('Schema: needs attention');
});
test('structured-output fixes are reviewed, not automatic, and undo restores input', async ({ page }) => {
  await page.goto('/json-schema-validator/');
  await page.locator('#doctor-structured').click();
  await expect(page.locator('#doctor-summary')).toContainText('Document: valid');
  const original = await page.locator('#doctor-schema').inputValue();
  await page.locator('#doctor-fixes summary').click();
  await expect(page.locator('#doctor-edit-list')).toContainText('Previously optional fields become required');
  expect(await page.locator('#doctor-schema').inputValue()).toBe(original);
  await page.locator('#doctor-apply').click();
  await expect(page.locator('#doctor-summary')).toContainText('Document: invalid');
  await expect(page.locator('#doctor-findings')).toContainText('Missing required property "category"');
  await page.locator('#doctor-undo').click();
  await expect(page.locator('#doctor-schema')).toHaveValue(original);
  await expect(page.locator('#doctor-summary')).toContainText('Document: valid');
});
test('share requires review, restores schema/document/settings, and makes no API calls', async ({ page }) => {
  const calls: string[] = [];
  page.on('request', request => { if (request.url().startsWith('https://api.bugdays.com')) calls.push(request.url()); });
  await page.addInitScript(() => { Object.defineProperty(navigator, 'clipboard', { value: { writeText: async (value: string) => { (window as any).__copied = value; } } }); });
  await page.goto('/json-schema-validator/');
  await page.locator('#doctor-invalid').click();
  await expect(page.locator('#doctor-findings .doctor-finding')).toHaveCount(4);
  await page.locator('#share-btn').click();
  await expect(page.locator('#doctor-share-review')).toBeVisible();
  await expect(page.locator('#doctor-review-continue')).toBeDisabled();
  await expect(page.locator('#doctor-share-preview')).toContainText('orderId');
  await page.locator('#doctor-share-ack').check();
  await page.locator('#doctor-review-continue').click();
  await page.locator('#share-url-btn').click();
  await expect.poll(() => page.evaluate(() => (window as any).__copied)).toContain('#lz:');
  const link = await page.evaluate(() => (window as any).__copied);
  await page.goto(link);
  await expect(page.locator('#doctor-findings .doctor-finding')).toHaveCount(4);
  expect(calls).toEqual([]);
});
test('local reference file validation, export, and no remote schema fetch', async ({ page }) => {
  const outbound: string[] = [];
  page.on('request', r => { if (r.url().includes('example.com')) outbound.push(r.url()); });
  await page.goto('/json-schema-validator/');
  await page.locator('#doctor-schema-file').setInputFiles({ name: 'root.json', mimeType: 'application/json', buffer: Buffer.from('{"$id":"https://example.com/root.json","$ref":"item.json"}') });
  await page.locator('#doctor-json-file').setInputFiles({ name: 'value.json', mimeType: 'application/json', buffer: Buffer.from('5') });
  await expect(page.locator('#doctor-findings')).toContainText('never fetched');
  await page.locator('#doctor-ref-files').setInputFiles({ name: 'item.json', mimeType: 'application/json', buffer: Buffer.from('{"$id":"https://example.com/item.json","type":"integer"}') });
  await expect(page.locator('#doctor-summary')).toContainText('Document: valid');
  const downloadPromise = page.waitForEvent('download'); await page.locator('#doctor-export').click();
  const download = await downloadPromise; expect(download.suggestedFilename()).toBe('json-schema-diagnosis.json');
  const stream = await download.createReadStream(); const chunks = [];
  for await (const chunk of stream!) chunks.push(chunk);
  const report = JSON.parse(Buffer.concat(chunks).toString()); expect(report.dataValid).toBe(true); expect(report.schema).toBeUndefined(); expect(report.json).toBeUndefined();
  expect(outbound).toEqual([]);
});
test('slow regex runs off-thread, times out, and a subsequent validation recovers', async ({ page }) => {
  await page.goto('/json-schema-validator/');
  await page.locator('#doctor-auto').uncheck();
  await page.locator('#doctor-schema').fill('{"type":"string","pattern":"^(a+)+$"}');
  await page.locator('#doctor-json').fill(JSON.stringify('a'.repeat(80) + '!'));
  await page.locator('#doctor-run').click();
  await expect(page.locator('#doctor-cancel')).toBeVisible();
  await expect(page.locator('#doctor-status')).toContainText('Stopped after 5 seconds', { timeout: 9000 });
  await page.locator('#doctor-valid').click();
  await expect(page.locator('#doctor-summary')).toContainText('Document: valid');
});
test('malicious shared content renders as text, cancellation and stale result handling', async ({ page }) => {
  const schema = { type: 'object', required: ['<img src=x onerror="window.__xss=1">'], additionalProperties: false };
  const hash = LZString.compressToEncodedURIComponent(JSON.stringify({ v: 1, t: 'json-schema-validator', a: 'validate', d: { schema: JSON.stringify(schema), json: '{}', dialect: 'auto', profile: 'standard', formats: false, references: [] } }));
  await page.goto(`/json-schema-validator/#lz:${hash}`);
  await expect(page.locator('#doctor-findings')).toContainText('<img');
  expect(await page.evaluate(() => (window as any).__xss)).toBeUndefined();
  await page.locator('#doctor-auto').uncheck();
  await page.locator('#doctor-json').fill('{"new":1}');
  await expect(page.locator('#doctor-export')).toBeDisabled();
  await expect(page.locator('#doctor-findings')).toBeEmpty();
  await page.locator('#doctor-schema').fill('{"type":"string","pattern":"^(a+)+$"}');
  await page.locator('#doctor-json').fill(JSON.stringify('a'.repeat(80) + '!'));
  await page.locator('#doctor-run').click(); await page.locator('#doctor-cancel').click();
  await expect(page.locator('#doctor-status')).toContainText('cancelled');
});
test('guide examples work and artwork/metadata are relevant and crawlable', async ({ page }) => {
  await page.goto('/guides/validate-json-against-schema/');
  await expect(page.locator('meta[property="og:image"]')).toHaveAttribute('content', 'https://bugdays.com/og/guide-json-schema-doctor.png');
  await expect(page.locator('.guide-article figure img')).toHaveJSProperty('naturalWidth', 1280);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('[data-schema-example="invalid"]').click();
  await expect(page.locator('#doctor-findings .doctor-finding')).toHaveCount(4);
  await page.goto('/guides/validate-json-against-schema/');
  await page.locator('[data-schema-example="valid"]').click();
  await expect(page.locator('#doctor-summary')).toContainText('Document: valid');
});
test('format safely, scroll a long schema to its last line, and keep heavy code deferred', async ({ page }) => {
  const workerRequests: string[] = [];
  page.on('request', r => { if (r.url().includes('schema-doctor.worker')) workerRequests.push(r.url()); });
  await page.goto('/json-schema-validator/');
  expect(workerRequests).toEqual([]);
  await page.locator('#doctor-auto').uncheck();
  await page.locator('#doctor-schema').fill('{"type":"object","type":"string"}');
  await page.locator('#doctor-format-schema').click();
  await expect(page.locator('#doctor-notice')).toContainText('Duplicate');
  await expect(page.locator('#doctor-schema')).toHaveValue('{"type":"object","type":"string"}');
  const longSchema = { type: 'object', properties: Object.fromEntries(Array.from({ length: 150 }, (_, i) => [`field${i}`, { type: 'string' }])) };
  await page.locator('#doctor-schema').fill(JSON.stringify(longSchema));
  await page.locator('#doctor-format-schema').click();
  await expect(page.locator('#doctor-schema')).toHaveValue(JSON.stringify(longSchema, null, 2));
  await page.locator('#doctor-schema').evaluate((input: HTMLTextAreaElement) => { input.scrollTop = input.scrollHeight; input.dispatchEvent(new Event('scroll')); });
  const bounds = await page.locator('#doctor-schema').evaluate((input: HTMLTextAreaElement) => ({ top: input.scrollTop, height: input.clientHeight, total: input.scrollHeight, transform: (input.parentElement!.querySelector('[data-json-editor-code]') as HTMLElement).style.transform }));
  expect(bounds.top + bounds.height).toBeGreaterThanOrEqual(bounds.total - 2);
  expect(bounds.transform).toContain(`${-bounds.top}px`);
});
test('shared local references and provider settings are restored together', async ({ page }) => {
  const data = { schema: '{"$id":"https://example.com/root.json","type":"object","properties":{"value":{"$ref":"value.json"}},"required":["value"],"additionalProperties":false}', json: '{"value":"bad-email"}', dialect: '2020-12', profile: 'openai', formats: true, references: ['{"$id":"https://example.com/value.json","type":"string","format":"email"}'] };
  const hash = LZString.compressToEncodedURIComponent(JSON.stringify({ v: 1, t: 'json-schema-validator', a: 'validate', d: data }));
  await page.goto(`/json-schema-validator/#lz:${hash}`);
  await expect(page.locator('#doctor-summary')).toContainText('Document: invalid');
  await expect(page.locator('#doctor-dialect')).toHaveValue('2020-12');
  await expect(page.locator('#doctor-profile')).toHaveValue('openai');
  await expect(page.locator('#doctor-formats')).toBeChecked();
  await expect(page.locator('#doctor-ref-count')).toHaveText('(1)');
  await expect(page.locator('#doctor-findings')).toContainText('email');
});
