export interface Guide {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  topic: string;
  published: string;
  updated: string;
  readingMinutes: number;
  image: string;
  /** Purpose-built on-page artwork. Keep `image` as a broadly compatible social-card image. */
  artImage?: string;
  imageAlt: string;
  toolHref: string;
  toolName: string;
}

export const guides: Guide[] = [
  {
    slug: 'epoch-iso8601-timezone-offset',
    title: 'Convert Epoch to ISO 8601 with the Correct Timezone Offset',
    shortTitle: 'Convert timestamps without timezone surprises',
    description: 'Convert Unix seconds or milliseconds to ISO 8601, interpret dates in an IANA timezone, handle daylight-saving gaps and overlaps, and share the exact moment.',
    topic: 'Unix timestamp and timezone conversion', published: '2026-10-07', updated: '2026-10-07', readingMinutes: 5,
    image: '/og/datetime-converter.png', artImage: '/og/datetime-converter.svg', imageAlt: 'One Unix timestamp displayed in UTC, New York, and Kolkata with correct ISO 8601 offsets',
    toolHref: '/datetime-converter/', toolName: 'Unix Timestamp & Timezone Converter',
  },
  {
    slug: 'compare-json-arrays-by-id-ignore-fields',
    title: 'Compare JSON Arrays by ID, Ignore Fields, and Export JSON Patch',
    shortTitle: 'Compare JSON records by ID, not position',
    description: 'Compare reordered JSON API records by a unique ID, ignore timestamps and request IDs, preserve exact numeric values, and share a runnable two-change example.',
    topic: 'JSON array matching and filtered comparisons', published: '2026-10-07', updated: '2026-10-07', readingMinutes: 6,
    image: '/og/json-diff.png', artImage: '/og/json-diff.svg', imageAlt: 'Reordered JSON records matched by ID, revealing a status change and exact large-number change while ignoring a timestamp',
    toolHref: '/json-diff/', toolName: 'JSON Diff and Compare',
  },
  {
    slug: 'json-large-integers-duplicate-keys',
    title: 'Why JSON Numbers Change and Duplicate Keys Disappear When Formatting',
    shortTitle: 'Keep exact JSON numbers and duplicate keys',
    description: 'Reproduce JSON.parse integer rounding and duplicate-key loss, then inspect and share JSON with exact digits, decimal notation, and every duplicate intact.',
    topic: 'JSON number precision and duplicate keys', published: '2026-10-07', updated: '2026-10-07', readingMinutes: 6,
    image: '/og/json-formatter.png', artImage: '/og/json-formatter.svg', imageAlt: 'JSON formatting preserves a large numeric ID and both duplicate status keys',
    toolHref: '/json-formatter/', toolName: 'JSON Formatter and Validator',
  },
  {
    slug: 'validate-json-against-schema',
    title: 'Validate JSON Against a Schema: Find and Fix the Failing Field',
    shortTitle: 'Diagnose JSON Schema validation errors',
    description: 'Debug a JSON API response with four reproducible failures. Understand required fields, null, extra keys, local references, and structured-output schema checks.',
    topic: 'JSON Schema validation', published: '2026-10-05', updated: '2026-10-05', readingMinutes: 7,
    image: '/og/guide-json-schema-doctor.png', artImage: '/og/guide-json-schema-doctor.svg',
    imageAlt: 'JSON Schema Doctor traces /items/0/quantity to its minimum rule, then shares the reproducible example',
    toolHref: '/json-schema-validator/', toolName: 'JSON Schema Doctor',
  },
  {
    slug: 'gzip-base64-java',
    title: 'Java GZip Base64: Compress and Decode Strings with UTF-8',
    shortTitle: 'Decode Base64 GZip in Java',
    description: 'Decode Base64 GZip in Java with a complete UTF-8 example. Fix GZIPInputStream errors, limit decompression, and share a runnable sample.',
    topic: 'Java payload decoding', published: '2026-10-01', updated: '2026-10-01', readingMinutes: 8,
    image: '/og/gzip-base64.png', imageAlt: 'GZip Base64 decoder showing a compressed payload beside the decoded JSON',
    toolHref: '/gzip-base64/', toolName: 'GZip Base64 Encoder and Decoder',
  },
  {
    slug: 'reset-kafka-consumer-group-offsets',
    title: 'Reset Kafka Consumer Group Offsets: Latest, Timestamp, or Exact Offset',
    shortTitle: 'Preview and reset Kafka offsets',
    description: 'Reset Kafka offsets by timestamp, earliest, latest, shift, or CSV. Preview selected partitions, save old positions, and apply a reviewed plan.',
    topic: 'Kafka offset reset procedures', published: '2026-10-01', updated: '2026-10-01', readingMinutes: 9,
    image: '/og/guide-kafka-offset-reset.png', artImage: '/og/guide-kafka-offset-reset.svg', imageAlt: 'Kafka partition offset reset from 9310 to a reviewed target, with earliest and latest boundaries',
    toolHref: '/kafka-diagnostics/', toolName: 'Kafka Consumer Diagnostics',
  },
  {
    slug: 'convert-curl-to-javascript-fetch-python-requests',
    title: 'Convert cURL to JavaScript Fetch or Python Requests',
    shortTitle: 'Convert a cURL command into reviewed code',
    description: 'Translate a common cURL command into JavaScript Fetch, Python requests, or readable cURL; verify methods, headers and bodies without executing a request, then share a redacted reproducer safely.',
    topic: 'cURL conversion and API request handoff', published: '2026-10-01', updated: '2026-10-01', readingMinutes: 6,
    image: '/og-image.png', artImage: '/og/guide-api-request-workflow.svg', imageAlt: 'A cURL request translated into JavaScript Fetch and Python requests',
    toolHref: '/curl-to-code/', toolName: 'cURL to JavaScript Fetch and Python Requests Converter',
  },
  {
    slug: 'jsonl-ndjson-viewer-validator',
    title: 'JSONL and NDJSON: Validate, Inspect, and Convert JSON Lines',
    shortTitle: 'Validate JSON Lines and convert valid records',
    description: 'Understand JSONL and NDJSON, isolate malformed line numbers without losing valid records, inspect a selected record, and export a safe JSON array for the next debugging step.',
    topic: 'JSON Lines and NDJSON debugging', published: '2026-10-01', updated: '2026-10-01', readingMinutes: 6,
    image: '/og-image.png', artImage: '/og/guide-json-inspection.svg', imageAlt: 'A JSON Lines document being validated with records and paths highlighted',
    toolHref: '/jsonl-viewer/', toolName: 'JSONL Viewer and NDJSON Validator',
  },
  {
    slug: 'format-sql-query-postgres-mysql-sql-server',
    title: 'Format SQL Queries and DDL for PostgreSQL, MySQL, and SQL Server',
    shortTitle: 'Format multi-dialect SQL and readable DDL',
    description: 'Choose the right SQL dialect, format queries and migrations for review, know the limits of pretty printing, and move CREATE TABLE scripts into an ER diagram workflow.',
    topic: 'SQL formatting and schema review', published: '2026-10-01', updated: '2026-10-01', readingMinutes: 6,
    image: '/og-image.png', artImage: '/og/guide-sql-formatting.svg', imageAlt: 'A formatted SQL query beside related database tables',
    toolHref: '/sql-formatter/', toolName: 'SQL Formatter and Beautifier',
  },
  {
    slug: 'json-to-typescript-zod-pydantic',
    title: 'Generate TypeScript, Zod, and Pydantic Models from JSON',
    shortTitle: 'Generate typed code from JSON',
    description: 'Turn a representative JSON response into TypeScript interfaces, Zod runtime schemas, or Pydantic models; learn how arrays, missing fields, nulls, and generated code need review.',
    topic: 'JSON type and model generation', published: '2026-10-01', updated: '2026-10-01', readingMinutes: 6,
    image: '/og-image.png', artImage: '/og/guide-json-inspection.svg', imageAlt: 'A structured JSON document ready for validation and code generation',
    toolHref: '/json-to-code/', toolName: 'JSON to TypeScript, Zod, and Pydantic Generator',
  },
  {
    slug: 'recover-dbeaver-saved-password-credentials-config',
    title: 'Recover a DBeaver Saved Password from credentials-config.json',
    shortTitle: 'Recover DBeaver saved credentials safely',
    description: 'Find DBeaver credentials-config.json, recover legacy or default saved connection credentials locally, and understand when master passwords or secure storage cannot be recovered.',
    topic: 'DBeaver credential recovery', published: '2026-10-01', updated: '2026-10-01', readingMinutes: 6,
    image: '/og/dbeaver-password-decrypter.png', imageAlt: 'Bug Days DBeaver credential recovery tool processing a local file in the browser',
    toolHref: '/dbeaver-password-decrypter/', toolName: 'DBeaver Password Decrypter',
  },
  {
    slug: 'cron-expression-next-run-timezone',
    title: 'Cron Expression Examples: Next Runs, Timezones, and Kubernetes',
    shortTitle: 'Test cron next runs and timezone assumptions',
    description: 'Read five-field cron syntax, preview upcoming executions, avoid timezone surprises, and understand the day-of-month and day-of-week rule used by Linux cron and Kubernetes CronJobs.',
    topic: 'Cron schedules and job timing', published: '2026-10-01', updated: '2026-10-01', readingMinutes: 6,
    image: '/og-image.png', artImage: '/og/guide-schedule-planner.svg', imageAlt: 'A cron expression with its upcoming scheduled run times',
    toolHref: '/cron-parser/', toolName: 'Cron Expression Parser and Generator',
  },
  {
    slug: 'base64-utf8-base64url-file-decoder',
    title: 'Base64 vs Base64URL: Padding, UTF-8, JWTs, and File Decoding',
    shortTitle: 'Decode Base64, Base64URL, and UTF-8 safely',
    description: 'Compare Base64 and Base64URL alphabets, fix padding, decode JWT segments, and preserve UTF-8 or file bytes with tested JavaScript examples.',
    topic: 'Base64 encoding and payload debugging', published: '2026-10-01', updated: '2026-10-01', readingMinutes: 7,
    image: '/og/guide-base64-variants.png', artImage: '/og/guide-base64-variants.svg', imageAlt: 'The same FB FF bytes encoded as standard Base64 +/8= and unpadded Base64URL -_8',
    toolHref: '/base64-encoder-decoder/', toolName: 'Base64 Encoder and Decoder',
  },
  {
    slug: 'format-validate-json-api-response',
    title: 'How to Format and Validate a JSON API Response',
    shortTitle: 'Format JSON and copy a jq path',
    description: 'Pretty-print an API response, troubleshoot invalid JSON, copy jq paths from a tree view, and share a runnable example. Includes jq and Python commands.',
    topic: 'JSON formatting and validation', published: '2026-10-01', updated: '2026-10-07', readingMinutes: 5,
    image: '/og/json-formatter.png', artImage: '/og/json-formatter.svg', imageAlt: 'A JSON formatter preserving exact numeric digits and duplicate keys',
    toolHref: '/json-formatter/', toolName: 'JSON Formatter and Validator',
  },
  {
    slug: 'compare-json-api-responses-ignore-array-order',
    title: 'Compare JSON API Responses: Ignore Key Order and Array Order',
    shortTitle: 'Compare JSON responses and reordered arrays',
    description: 'Find changes in JSON API responses and configuration files. Try a shareable example, compare reordered arrays, and distinguish duplicates, nulls, and missing fields.',
    topic: 'JSON comparison and debugging', published: '2026-10-01', updated: '2026-10-07', readingMinutes: 5,
    image: '/og/json-diff.png', artImage: '/og/json-diff.svg', imageAlt: 'JSON records matched by ID with exact changed values and shareable comparison settings',
    toolHref: '/json-diff/', toolName: 'JSON Diff Checker',
  },
  {
    slug: 'diagnose-kafka-consumer-lag-stuck-partition',
    title: 'Diagnose Kafka Consumer Lag and a Stuck Partition',
    shortTitle: 'Diagnose Kafka consumer lag',
    description: 'Diagnose Kafka consumer lag with two snapshots: find stalled partitions, unexpected group members, uneven assignments, and possible poison-pill records.',
    topic: 'Kafka consumer diagnostics', published: '2026-09-24', updated: '2026-10-01', readingMinutes: 8,
    image: '/og/guide-kafka-lag.png', artImage: '/og/guide-kafka-lag.svg', imageAlt: 'Kafka lag growing from 50 to 79 while partition 2 stays committed at offset 9310',
    toolHref: '/kafka-diagnostics/', toolName: 'Kafka Consumer Diagnostics',
  },
  {
    slug: 'browse-kafka-messages-by-offset-time',
    title: 'How to Browse Kafka Messages by Offset, Timestamp, and Partition',
    shortTitle: 'Browse Kafka records by offset or time',
    description: 'Read an exact Kafka offset range or start at a UTC timestamp, inspect key and headers, and understand retention and compaction gaps.',
    topic: 'Kafka message inspection', published: '2026-09-24', updated: '2026-09-24', readingMinutes: 6,
    image: '/og-image.png', artImage: '/og/guide-kafka-operations.svg', imageAlt: 'Kafka topic partitions with committed and end offsets for message inspection',
    toolHref: '/kafka-client/', toolName: 'Kafka Message Browser',
  },
  {
    slug: 'replay-kafka-messages-between-topics',
    title: 'How to Replay Kafka Messages to Another Topic or Cluster',
    shortTitle: 'Replay Kafka messages safely',
    description: 'Copy a Kafka record or bounded offset range to the same or another cluster, preserving key, value, headers, and partition order where possible.',
    topic: 'Kafka message replay', published: '2026-09-24', updated: '2026-09-24', readingMinutes: 7,
    image: '/og-image.png', artImage: '/og/guide-kafka-operations.svg', imageAlt: 'Kafka topic partitions used to inspect and replay a bounded offset range',
    toolHref: '/kafka-client/', toolName: 'Kafka Message Browser',
  },
  {
    slug: 'check-tls-certificate-chain-any-port',
    title: 'How to Check a TLS Certificate Chain, Expiry, SAN, and SNI on Any Port',
    shortTitle: 'Check a TLS certificate chain on any port',
    description: 'Inspect the certificate chain a live HTTPS, Kafka SSL, LDAPS, SMTPS, IMAPS, or raw TLS service presents; diagnose expiry, SAN mismatch, SNI, trust, and missing intermediates.',
    topic: 'TLS certificates and service diagnostics',
    published: '2026-09-16',
    updated: '2026-10-01',
    readingMinutes: 9,
    image: '/og/certificate-inspector.png',
    imageAlt: 'TLS certificate chain checker reporting expiry, SAN hostname match, SNI, trust, and every certificate presented by a service',
    toolHref: '/certificate-inspector/',
    toolName: 'TLS Certificate Chain Checker',
  },
  {
    slug: 'dns-lookup-public-vs-system-resolver',
    title: 'DNS Lookup Guide: Compare Public, System, VPN, and Reverse DNS',
    shortTitle: 'Compare public, system, VPN, and reverse DNS',
    description: 'Check A, AAAA, CNAME, MX, TXT, NS, SOA, SRV, CAA, and PTR records; understand split-horizon DNS and forward-confirm a reverse DNS hostname.',
    topic: 'DNS and network diagnostics',
    published: '2026-09-16',
    updated: '2026-09-16',
    readingMinutes: 8,
    image: '/og-image.png',
    artImage: '/og/guide-network-investigation.svg',
    imageAlt: 'An IP address connected to reverse DNS, ASN, and network range evidence',
    toolHref: '/dns-lookup/',
    toolName: 'DNS Lookup and Reverse DNS Checker',
  },
  {
    slug: 'ip-address-lookup-isp-asn-reverse-dns',
    title: 'How to Look Up an IP Address: ISP, ASN, Location, and Reverse DNS',
    shortTitle: 'Look up an IP address and its network',
    description: 'Learn what an IP address lookup can reveal about an ISP, ASN, network owner, approximate location, reverse DNS, and cloud provider—and what it cannot prove.',
    topic: 'IP and network investigation',
    published: '2026-09-15',
    updated: '2026-09-15',
    readingMinutes: 8,
    image: '/og-image.png',
    artImage: '/og/guide-network-investigation.svg',
    imageAlt: 'An IP address lookup connecting reverse DNS, ASN, and range evidence',
    toolHref: '/ip-lookup/',
    toolName: 'IP Address, ISP and Cloud Lookup',
  },
  {
    slug: 'identify-cloud-hosting-ips-in-access-logs',
    title: 'How to Identify Cloud, Hosting, and Crawler IPs in Access Logs',
    shortTitle: 'Identify hosting IPs in access logs',
    description: 'Investigate access-log IPs against cloud provider feeds, hosting ASN prefixes, CDN networks, and published crawler ranges without mistaking infrastructure for intent.',
    topic: 'Network and bot investigation',
    published: '2026-09-15',
    updated: '2026-10-01',
    readingMinutes: 9,
    image: '/og/guide-access-log-evidence.png',
    artImage: '/og/guide-access-log-evidence.svg',
    imageAlt: 'Access-log investigation: establish the source IP, check network evidence, then compare request behavior',
    toolHref: '/ip-lookup/',
    toolName: 'IP Address, ISP and Cloud Lookup',
  },
  {
    slug: 'test-grpc-api-proto-metadata-streaming',
    title: 'How to Test a gRPC API: Proto Files, Metadata, and Streaming',
    shortTitle: 'Test a gRPC API from its proto file',
    description: 'A practical gRPC testing workflow: load a proto contract, choose a method, build protobuf data from JSON, send metadata, inspect trailers, and debug status codes.',
    topic: 'gRPC and APIs',
    published: '2026-09-14',
    updated: '2026-09-14',
    readingMinutes: 9,
    image: '/og/grpc-client.png',
    imageAlt: 'gRPC API client showing a proto service, JSON request, decoded response messages, metadata, and trailers',
    toolHref: '/grpc-client/',
    toolName: 'gRPC API Client',
  },
  {
    slug: 'grpc-web-vs-native-grpc-browser-testing',
    title: 'gRPC-Web vs Native gRPC: How Browser Testing Actually Works',
    shortTitle: 'Understand gRPC-Web and native gRPC testing',
    description: 'Choose the correct browser transport for a gRPC service, understand when gRPC-Web works directly, and test native HTTP/2 gRPC through a local bridge.',
    topic: 'gRPC and browsers',
    published: '2026-09-14',
    updated: '2026-09-14',
    readingMinutes: 7,
    image: '/og/grpc-client.png',
    imageAlt: 'Browser gRPC client offering native gRPC through a local bridge and direct gRPC-Web transport',
    toolHref: '/grpc-client/',
    toolName: 'Native gRPC and gRPC-Web Client',
  },
  {
    slug: 'soap-api-authentication-basic-ws-security-mtls',
    title: 'SOAP API Authentication: Basic Auth, WS-Security, and mTLS',
    shortTitle: 'Debug SOAP authentication',
    description: 'Test SOAP Basic auth and WS-Security UsernameToken PasswordText or PasswordDigest, and separate HTTP, message-security, and mTLS failures.',
    topic: 'SOAP and security',
    published: '2026-09-14',
    updated: '2026-10-07',
    readingMinutes: 8,
    image: '/og/soap-client.png',
    imageAlt: 'SOAP API client with authentication controls, SOAPAction, XML request editor, and response inspection',
    toolHref: '/soap-client/',
    toolName: 'SOAP API Client',
  },
  {
    slug: 'decode-base64-gzip-to-json',
    title: 'Decode Base64 GZip to JSON: A Worked Example',
    shortTitle: 'Decode a Base64 GZip payload',
    description: 'Decode a Base64 GZip string into readable JSON, understand the H4sI prefix, and share a working example that opens directly in the browser tool.',
    topic: 'Payload decoding',
    published: '2026-09-06',
    updated: '2026-10-07',
    readingMinutes: 6,
    image: '/og/gzip-base64.png',
    imageAlt: 'GZip Base64 decoder with a compressed sample and its readable JSON output',
    toolHref: '/gzip-base64/',
    toolName: 'GZip Base64 Encoder and Decoder',
  },
  {
    slug: 'read-java-thread-dump-find-deadlock',
    title: 'How to Read a Java Thread Dump and Find a Deadlock',
    shortTitle: 'Find a Java deadlock in a thread dump',
    description: 'A practical, evidence-first method for reading jstack and jcmd output, tracing monitor ownership, confirming deadlocks, and separating ordinary waits from incidents.',
    topic: 'JVM diagnostics',
    published: '2026-09-05',
    updated: '2026-09-05',
    readingMinutes: 8,
    image: '/og/thread-dump-analyzer.png',
    imageAlt: 'Java thread dump analyzer showing blocked threads, lock owners, and a deadlock cycle',
    toolHref: '/thread-dump-analyzer/',
    toolName: 'Java Thread Dump Analyzer',
  },
  {
    slug: 'pem-vs-der-vs-cer-vs-p7b-certificate-formats',
    title: 'PEM vs DER vs CER vs P7B: Certificate Formats Explained',
    shortTitle: 'PEM, DER, CER, and P7B explained',
    description: 'Identify common X.509 certificate formats, inspect their contents, convert them safely with OpenSSL, and avoid confusing filename extensions with encodings.',
    topic: 'TLS and certificates',
    published: '2026-09-05',
    updated: '2026-09-05',
    readingMinutes: 7,
    image: '/og/certificate-inspector.png',
    imageAlt: 'X.509 certificate inspector showing identity, validity, fingerprints, and conversion options',
    toolHref: '/certificate-inspector/',
    toolName: 'X.509 Certificate Inspector',
  },
  {
    slug: 'test-soap-api-from-wsdl-soap-11-vs-12',
    title: 'How to Test a SOAP API from a WSDL: SOAP 1.1 vs 1.2',
    shortTitle: 'Test a SOAP API from its WSDL',
    description: 'Generate SOAP requests from WSDL and linked XSD types, handle JAX-WS namespaces and RPC bindings, choose SOAP 1.1 or 1.2, and debug faults.',
    topic: 'SOAP and APIs',
    published: '2026-09-05',
    updated: '2026-10-07',
    readingMinutes: 10,
    image: '/og/soap-client.png',
    imageAlt: 'SOAP client with WSDL operation browser, XML request editor, and response inspector',
    toolHref: '/soap-client/',
    toolName: 'SOAP and WSDL Client',
  },
  {
    slug: 'sql-ddl-to-er-diagram-data-dictionary',
    title: 'How to Turn SQL DDL into an ER Diagram and Data Dictionary',
    shortTitle: 'Turn SQL DDL into an ER diagram',
    description: 'Extract a schema-only database definition, visualize foreign-key relationships, add useful annotations, and export documentation without connecting another service.',
    topic: 'Database documentation',
    published: '2026-09-05',
    updated: '2026-09-05',
    readingMinutes: 7,
    image: '/og/schema-explorer.png',
    imageAlt: 'Interactive entity relationship diagram generated from SQL DDL',
    toolHref: '/schema-explorer/',
    toolName: 'Database Schema Explorer',
  },
  {
    slug: 'convert-terminal-table-to-excel',
    title: 'How to Convert a Terminal Table to Excel Without Broken Columns',
    shortTitle: 'Convert terminal output to Excel',
    description: 'Turn ASCII pipes, Unicode box drawing, PostgreSQL results, or aligned console output into editable Excel, CSV, HTML, Word, and printable tables.',
    topic: 'Terminal productivity',
    published: '2026-09-05',
    updated: '2026-09-05',
    readingMinutes: 6,
    image: '/og/ascii-table-converter.png',
    imageAlt: 'Terminal ASCII table converted into editable spreadsheet rows and columns',
    toolHref: '/ascii-table-converter/',
    toolName: 'Terminal Table Converter',
  },
  {
    slug: 'gzip-base64-python-nodejs',
    title: 'GZip + Base64 in Python and Node.js: Matching Examples',
    shortTitle: 'GZip and Base64 in Python and Node.js',
    description: 'Compress UTF-8 text to Base64 GZip in Python and Node.js, decode it across languages, and compare the results with a runnable browser example.',
    topic: 'Encoding recipes',
    published: '2026-09-06',
    updated: '2026-09-06',
    readingMinutes: 5,
    image: '/og/gzip-base64.png',
    imageAlt: 'Browser GZip Base64 tool for checking compressed payloads from Python and Node.js',
    toolHref: '/gzip-base64/',
    toolName: 'GZip Base64 Encoder and Decoder',
  },
  {
    slug: 'fix-base64-gzip-decode-errors',
    title: 'Base64 GZip Decode Errors: Padding, Headers, and H4sI',
    shortTitle: 'Find why a Base64 GZip payload will not decode',
    description: 'Diagnose invalid Base64, incorrect GZip headers, truncated payloads, and unreadable output. Compare your input with a working, shareable example.',
    topic: 'Decoding troubleshooting',
    published: '2026-09-06',
    updated: '2026-10-07',
    readingMinutes: 6,
    image: '/og/gzip-base64.png',
    imageAlt: 'A known-good Base64 GZip sample decoded into readable text in Bug Days',
    toolHref: '/gzip-base64/',
    toolName: 'GZip Base64 Encoder and Decoder',
  },
];

export function guideBySlug(slug: string): Guide {
  const guide = guides.find((item) => item.slug === slug);
  if (!guide) throw new Error(`Unknown guide: ${slug}`);
  return guide;
}
