export interface Guide {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  topic: string;
  published: string;
  updated: string;
  readingMinutes: number;
  image: string;
  imageAlt: string;
  toolHref: string;
  toolName: string;
}

export const guides: Guide[] = [
  {
    slug: 'check-tls-certificate-chain-any-port',
    title: 'How to Check a TLS Certificate Chain, Expiry, SAN, and SNI on Any Port',
    shortTitle: 'Check a TLS certificate chain on any port',
    description: 'Inspect the certificate chain a live HTTPS, Kafka SSL, LDAPS, SMTPS, IMAPS, or raw TLS service presents; diagnose expiry, SAN mismatch, SNI, trust, and missing intermediates.',
    topic: 'TLS certificates and service diagnostics',
    published: '2026-09-16',
    updated: '2026-09-16',
    readingMinutes: 9,
    image: '/og/certificate-inspector.png',
    imageAlt: 'TLS certificate chain checker reporting expiry, SAN hostname match, SNI, trust, and every certificate presented by a service',
    toolHref: '/certificate-inspector',
    toolName: 'TLS Certificate Chain Checker',
  },
  {
    slug: 'dns-lookup-public-vs-system-resolver',
    title: 'DNS Lookup Guide: Compare Public, System, VPN, and Reverse DNS',
    shortTitle: 'Compare public, system, VPN, and reverse DNS',
    description: 'Check A, AAAA, CNAME, MX, TXT, NS, SOA, SRV, CAA, and PTR records; understand split-horizon DNS and forward-confirm a reverse DNS hostname.',
    topic: 'DNS and network diagnostics',
    published: '2026-09-16',
    updated: '2026-09-16',
    readingMinutes: 8,
    image: '/og-image.png',
    imageAlt: 'DNS lookup report comparing public resolver answers with device and VPN DNS plus a PTR reverse lookup',
    toolHref: '/dns-lookup',
    toolName: 'DNS Lookup and Reverse DNS Checker',
  },
  {
    slug: 'ip-address-lookup-isp-asn-reverse-dns',
    title: 'How to Look Up an IP Address: ISP, ASN, Location, and Reverse DNS',
    shortTitle: 'Look up an IP address and its network',
    description: 'Learn what an IP address lookup can reveal about an ISP, ASN, network owner, approximate location, reverse DNS, and cloud provider—and what it cannot prove.',
    topic: 'IP and network investigation',
    published: '2026-09-15',
    updated: '2026-09-15',
    readingMinutes: 8,
    image: '/og-image.png',
    imageAlt: 'Bug Days IP address lookup report showing ISP, ASN, approximate location, reverse DNS, and cloud provider evidence',
    toolHref: '/ip-lookup',
    toolName: 'IP Address, ISP and Cloud Lookup',
  },
  {
    slug: 'identify-cloud-hosting-ips-in-access-logs',
    title: 'How to Identify Cloud, Hosting, and Crawler IPs in Access Logs',
    shortTitle: 'Identify hosting IPs in access logs',
    description: 'Investigate access-log IPs against cloud provider feeds, hosting ASN prefixes, CDN networks, and published crawler ranges without mistaking infrastructure for intent.',
    topic: 'Network and bot investigation',
    published: '2026-09-15',
    updated: '2026-09-15',
    readingMinutes: 8,
    image: '/og-image.png',
    imageAlt: 'Bug Days network investigation workflow for matching access-log addresses to cloud, hosting, CDN, and crawler ranges',
    toolHref: '/ip-lookup',
    toolName: 'IP Address, ISP and Cloud Lookup',
  },
  {
    slug: 'test-grpc-api-proto-metadata-streaming',
    title: 'How to Test a gRPC API: Proto Files, Metadata, and Streaming',
    shortTitle: 'Test a gRPC API from its proto file',
    description: 'A practical gRPC testing workflow: load a proto contract, choose a method, build protobuf data from JSON, send metadata, inspect trailers, and debug status codes.',
    topic: 'gRPC and APIs',
    published: '2026-09-14',
    updated: '2026-09-14',
    readingMinutes: 9,
    image: '/og/grpc-client.png',
    imageAlt: 'gRPC API client showing a proto service, JSON request, decoded response messages, metadata, and trailers',
    toolHref: '/grpc-client',
    toolName: 'gRPC API Client',
  },
  {
    slug: 'grpc-web-vs-native-grpc-browser-testing',
    title: 'gRPC-Web vs Native gRPC: How Browser Testing Actually Works',
    shortTitle: 'Understand gRPC-Web and native gRPC testing',
    description: 'Choose the correct browser transport for a gRPC service, understand when gRPC-Web works directly, and test native HTTP/2 gRPC through a local bridge.',
    topic: 'gRPC and browsers',
    published: '2026-09-14',
    updated: '2026-09-14',
    readingMinutes: 7,
    image: '/og/grpc-client.png',
    imageAlt: 'Browser gRPC client offering native gRPC through a local bridge and direct gRPC-Web transport',
    toolHref: '/grpc-client',
    toolName: 'Native gRPC and gRPC-Web Client',
  },
  {
    slug: 'soap-api-authentication-basic-ws-security-mtls',
    title: 'SOAP API Authentication: Basic Auth, WS-Security, and mTLS',
    shortTitle: 'Debug SOAP authentication',
    description: 'Identify which SOAP authentication layer a service expects, test HTTP credentials safely, recognize WS-Security headers, and separate mTLS failures from SOAP faults.',
    topic: 'SOAP and security',
    published: '2026-09-14',
    updated: '2026-09-14',
    readingMinutes: 8,
    image: '/og/soap-client.png',
    imageAlt: 'SOAP API client with authentication controls, SOAPAction, XML request editor, and response inspection',
    toolHref: '/soap-client',
    toolName: 'SOAP API Client',
  },
  {
    slug: 'decode-base64-gzip-to-json',
    title: 'Decode Base64 GZip to JSON: A Worked Example',
    shortTitle: 'Decode a Base64 GZip payload',
    description: 'Decode a Base64 GZip string into readable JSON, understand the H4sI prefix, and share a working example that opens directly in the browser tool.',
    topic: 'Payload decoding',
    published: '2026-09-06',
    updated: '2026-09-06',
    readingMinutes: 4,
    image: '/og/gzip-base64.png',
    imageAlt: 'GZip Base64 decoder with a compressed sample and its readable JSON output',
    toolHref: '/gzip-base64',
    toolName: 'GZip Base64 Encoder and Decoder',
  },
  {
    slug: 'read-java-thread-dump-find-deadlock',
    title: 'How to Read a Java Thread Dump and Find a Deadlock',
    shortTitle: 'Find a Java deadlock in a thread dump',
    description: 'A practical, evidence-first method for reading jstack and jcmd output, tracing monitor ownership, confirming deadlocks, and separating ordinary waits from incidents.',
    topic: 'JVM diagnostics',
    published: '2026-09-05',
    updated: '2026-09-05',
    readingMinutes: 8,
    image: '/og/thread-dump-analyzer.png',
    imageAlt: 'Java thread dump analyzer showing blocked threads, lock owners, and a deadlock cycle',
    toolHref: '/thread-dump-analyzer',
    toolName: 'Java Thread Dump Analyzer',
  },
  {
    slug: 'pem-vs-der-vs-cer-vs-p7b-certificate-formats',
    title: 'PEM vs DER vs CER vs P7B: Certificate Formats Explained',
    shortTitle: 'PEM, DER, CER, and P7B explained',
    description: 'Identify common X.509 certificate formats, inspect their contents, convert them safely with OpenSSL, and avoid confusing filename extensions with encodings.',
    topic: 'TLS and certificates',
    published: '2026-09-05',
    updated: '2026-09-05',
    readingMinutes: 7,
    image: '/og/certificate-inspector.png',
    imageAlt: 'X.509 certificate inspector showing identity, validity, fingerprints, and conversion options',
    toolHref: '/certificate-inspector',
    toolName: 'X.509 Certificate Inspector',
  },
  {
    slug: 'test-soap-api-from-wsdl-soap-11-vs-12',
    title: 'How to Test a SOAP API from a WSDL: SOAP 1.1 vs 1.2',
    shortTitle: 'Test a SOAP API from its WSDL',
    description: 'Turn a WSDL operation into a working request, choose the right SOAP version and headers, interpret faults, and recognize browser CORS limitations.',
    topic: 'SOAP and APIs',
    published: '2026-09-05',
    updated: '2026-09-14',
    readingMinutes: 8,
    image: '/og/soap-client.png',
    imageAlt: 'SOAP client with WSDL operation browser, XML request editor, and response inspector',
    toolHref: '/soap-client',
    toolName: 'SOAP and WSDL Client',
  },
  {
    slug: 'sql-ddl-to-er-diagram-data-dictionary',
    title: 'How to Turn SQL DDL into an ER Diagram and Data Dictionary',
    shortTitle: 'Turn SQL DDL into an ER diagram',
    description: 'Extract a schema-only database definition, visualize foreign-key relationships, add useful annotations, and export documentation without connecting another service.',
    topic: 'Database documentation',
    published: '2026-09-05',
    updated: '2026-09-05',
    readingMinutes: 7,
    image: '/og/schema-explorer.png',
    imageAlt: 'Interactive entity relationship diagram generated from SQL DDL',
    toolHref: '/schema-explorer',
    toolName: 'Database Schema Explorer',
  },
  {
    slug: 'convert-terminal-table-to-excel',
    title: 'How to Convert a Terminal Table to Excel Without Broken Columns',
    shortTitle: 'Convert terminal output to Excel',
    description: 'Turn ASCII pipes, Unicode box drawing, PostgreSQL results, or aligned console output into editable Excel, CSV, HTML, Word, and printable tables.',
    topic: 'Terminal productivity',
    published: '2026-09-05',
    updated: '2026-09-05',
    readingMinutes: 6,
    image: '/og/ascii-table-converter.png',
    imageAlt: 'Terminal ASCII table converted into editable spreadsheet rows and columns',
    toolHref: '/ascii-table-converter',
    toolName: 'Terminal Table Converter',
  },
  {
    slug: 'gzip-base64-python-nodejs',
    title: 'GZip + Base64 in Python and Node.js: Matching Examples',
    shortTitle: 'GZip and Base64 in Python and Node.js',
    description: 'Compress UTF-8 text to Base64 GZip in Python and Node.js, decode it across languages, and compare the results with a runnable browser example.',
    topic: 'Encoding recipes',
    published: '2026-09-06',
    updated: '2026-09-06',
    readingMinutes: 5,
    image: '/og/gzip-base64.png',
    imageAlt: 'Browser GZip Base64 tool for checking compressed payloads from Python and Node.js',
    toolHref: '/gzip-base64',
    toolName: 'GZip Base64 Encoder and Decoder',
  },
  {
    slug: 'fix-base64-gzip-decode-errors',
    title: 'Base64 GZip Decode Errors: Padding, Headers, and H4sI',
    shortTitle: 'Find why a Base64 GZip payload will not decode',
    description: 'Diagnose invalid Base64, incorrect GZip headers, truncated payloads, and unreadable output. Compare your input with a working, shareable example.',
    topic: 'Decoding troubleshooting',
    published: '2026-09-06',
    updated: '2026-09-06',
    readingMinutes: 5,
    image: '/og/gzip-base64.png',
    imageAlt: 'A known-good Base64 GZip sample decoded into readable text in Bug Days',
    toolHref: '/gzip-base64',
    toolName: 'GZip Base64 Encoder and Decoder',
  },
];

export function guideBySlug(slug: string): Guide {
  const guide = guides.find((item) => item.slug === slug);
  if (!guide) throw new Error(`Unknown guide: ${slug}`);
  return guide;
}
